# Generated by Django 5.0.14 on 2025-06-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='default123', max_length=128),
            preserve_default=False,
        ),
    ]
