# Generated by Django 5.2.3 on 2025-06-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealer',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
