# Generated by Django 5.2.3 on 2025-06-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dealer_is_verified_dealer_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(choices=[('dealer', 'Dealer'), ('company', 'Company')], max_length=20)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
