# Generated by Django 5.2.3 on 2025-06-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_loginrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='contact_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_person',
        ),
    ]
