# Generated by Django 5.0.14 on 2025-06-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_contact_email_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
