# Generated by Django 5.0.14 on 2025-06-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dealer_is_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='is_notified',
        ),
    ]
