# Generated by Django 5.0.14 on 2025-06-28 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_dealer_is_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('client_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_gst_number', models.CharField(blank=True, max_length=30, null=True)),
                ('client_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('client_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('installation_date', models.DateField()),
                ('installed_by', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_by_id', models.CharField(max_length=100)),
                ('submitted_by_role', models.CharField(max_length=100)),
                ('submitted_by_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Machine_install/')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_set', to='api.machineinstallation')),
            ],
        ),
    ]
