# Generated by Django 5.0.14 on 2025-07-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigner',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee_id',
            field=models.CharField(default='user_1', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='assigner_id',
            field=models.CharField(default='user_1', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='machine_id',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
