# Generated by Django 5.0.14 on 2025-07-02 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_task_assignee_remove_task_assigner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loginrecord',
            options={'ordering': ['-login_time']},
        ),
        migrations.AlterModelOptions(
            name='machineinstallation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Machine Installation'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='installationphoto',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.machineinstallation'),
        ),
        migrations.AlterField(
            model_name='installationphoto',
            name='photo',
            field=models.ImageField(upload_to='machine_install/'),
        ),
        migrations.AlterField(
            model_name='machineinstallation',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In\xa0Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
