# Generated by Django 4.2 on 2025-07-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_no', models.CharField(db_column='panno', max_length=20)),
                ('accountname', models.CharField(db_column='accountname', max_length=255)),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('gstno', models.CharField(db_column='gstno', max_length=20)),
            ],
            options={
                'db_table': 'accountmaster',
                'managed': False,
            },
        ),
    ]
