# Generated by Django 4.2 on 2025-07-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_machineinstallation_model_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineinstallation',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
