# Generated by Django 5.0.14 on 2025-07-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_machineinstallation_batch_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineinstallation',
            name='serial_number',
        ),
    ]
