# Generated by Django 4.2 on 2025-09-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_machineinstallation_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='gst_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='user_type',
            field=models.CharField(choices=[('dealer', 'Dealer'), ('company', 'Company'), ('employee', 'Employee')], max_length=20),
        ),
    ]
