# Generated by Django 5.2.11 on 2026-03-05 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_dealer_gst_no_alter_loginrecord_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('SalesInvoiceId', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False)),
                ('DocumentNo', models.IntegerField()),
                ('DocumentDate', models.DateField()),
            ],
            options={
                'db_table': 'SalesInvoice',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigner_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='machine_id',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_tasks', to='api.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_tasks', to='api.company'),
        ),
    ]
