# Generated by Django 5.2.11 on 2026-03-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_department_ticketcategory_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='vin',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
