# Generated by Django 4.2 on 2025-07-19 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_accountmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineinstallation',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='machineinstallation',
            name='submitted_by_id',
        ),
        migrations.AddField(
            model_name='machineinstallation',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machineinstallation',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineinstallation',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineinstallation',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_installations', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='machineinstallation',
            name='batch_number',
            field=models.CharField(db_index=True, default='TEMP_BATCH', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='machineinstallation',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
